name: wine-quality-model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://chaivan/mlops_test:firsttry
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip3 install -r requirements.txt
          python3 train.py
          
          echo "MODEL METRICS"
          cat metrics.txt
